### ISSUE TITLE
Convert image sizes to 4K res

### ISSUE THREAD

**Issue by JPeisach** [UbuntuDDE/deepin-wallpapers#1]
in ./blur(something).sh:

do
        picname=${inname//jpg/bmp}
        convert -resize 1920x1080 ./deepin/$inname ./deepin/$picname 
        rm -rf ./deepin/$inname
    done

I suggest instead of resizing to 1920x1080, try to pick a 4K resolution size (the resolution in consumer media, not in movie production), e.g.  3840 × 2160.

If you want to remake the makefile, all the instructions are in budgie-wallpapers in their GitHub and they use ImageMagick and Mozjpeg w/ jhead, same thing we use. Let me know if you're interested.

**Comment by openarun** [comment]
That part of code is for other architectures.
