### ISSUE TITLE
Installation paths-separating deepin from DDE

### ISSUE THREAD

**Issue by JPeisach** [UbuntuDDE/deepin-wallpapers#2]
Deepin wallpapers are great, but blending them in with DDE just doesn't seem right. Always nice to give credit to our upstream for their hard work :)

I suggest two folders:
**deepin** - For Deepin Wallpapers
**"ubuntudde"**, or **"dderemix"**, or **"dde-remix"**

**Comment by openarun** [comment]
Yes, we're using this package temporarily. We'll have ubuntudde-wallpapers. And all the credits are given to them as they were. Not an issue with that.
