### ISSUE TITLE
Discussion: XML Files/support for wallpapers

### ISSUE THREAD

**Issue by JPeisach** [UbuntuDDE/deepin-wallpapers#3]
In pretty much almost every desktop, all wallpapers are assigned to by a .xml file (see ubuntucinnamon-wallpapers and budgie-wallpapers package) to allow the desktop to fully allow them in use. How exactly do they work here? Are xml's being used or is something else happening?

TL;DR/want a nutshell: We have .xml files to allow the desktop to have connection to the image, allowing it to be used for real. What is the story here?

**Comment by openarun** [comment]
In DDE v5.0.0 there is no support for xml for wallpapers from the upstream yet. 
Doesn't sound like our concern here.
