### ISSUE TITLE
Confusing wallpaper package names

### ISSUE THREAD

**Issue by JPeisach** [UbuntuDDE/deepin-wallpapers#4]
What is this package supposed to be called? Isn't deepin-wallpapers a thing in Deepin, as in their repo? For maintaining in Debian, and here in a PPA in Launchpad, these two can be confusing-I suggest a rename to something such as ubuntudde-wallpapers, dderemix-wallpapers, etc.

**Comment by openarun** [comment]
I am aware of it. dupe of #2 .
